name: flutter_suite
description: Flutter Suite is a super-effective and lightweight solution for Flutter.
version: 0.1.8
homepage: https://github.com/rahulsharmadev-community
repository: https://github.com/rahulsharmadev-community/flutter_suite
documentation: https://github.com/rahulsharmadev-community/flutter_suite/blob/master/README.md
issue_tracker: https://github.com/rahulsharmadev-community/flutter_suite/issues

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  meta: ^1.12.0
  dart_suite:
    path: ../dart_suite

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
