name: dart_suite
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/rahulsharmadev-community/jars/blob/main/packages/dart_suite

environment:
  sdk: ">=3.3.2 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  crypto: ">=3.0.5"
  collection: ">=1.18.0"
  meta: ^1.12.0
  intl: ">=0.19.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
