name: regpatterns
description: A powerful tool for working with regular expressions in Dart.
version: 0.0.9
repository: https://github.com/rahulsharmadev-community/jars/blob/main/packages/regpatterns
documentation: https://github.com/rahulsharmadev-community/jars/blob/main/packages/regpatterns/README.md
issue_tracker: https://github.com/rahulsharmadev-community/jars/issues

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.3.2 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
