name: jars
description: JARS is a super-effective and lightweight solution for Flutter.
version: 0.1.7
homepage: https://github.com/rahulsharmadev-community
repository: https://github.com/rahulsharmadev-community/jars
documentation: https://github.com/rahulsharmadev-community/jars/blob/master/README.md
issue_tracker: https://github.com/rahulsharmadev-community/jars/issues

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ">=8.1.6"
  go_router: ">=14.2.0"
  logger: ">=2.3.0"
  meta: ^1.12.0

  jars_core:
    path: ../jars_core
  regpatterns:
    path: ../regpatterns
  bloc_utils:
    path: ../bloc_utils
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
