name: jars_core
description: A starting point for Dart libraries or applications.
version: 0.1.1
repository: https://github.com/rahulsharmadev-community/jars/blob/main/packages/jars_core

environment:
  sdk: ^3.3.2


platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  regpatterns:
    git:
      url: https://github.com/rahulsharmadev-community/jars.git
      ref: main
      path: packages/regpatterns

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
