name: jars_core
description: A starting point for Dart libraries or applications.
version: 0.1.6
repository: https://github.com/rahulsharmadev-community/jars/blob/main/packages/jars_core

environment:
  sdk: ^3.3.2

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  collection: ^1.18.0
  meta: ^1.12.0
  intl: ^0.19.0


  # regpatterns:
  #   git:
  #     url: https://github.com/rahulsharmadev-community/jars.git
  #     ref: main
  #     path: packages/regpatterns

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
